# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'flutter-boost-ios' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for flutter-boost-ios

#   通过官方推荐方法1
  flutter_application_path = '../flutter_module/'
  load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')
  install_all_flutter_pods(flutter_application_path)

  #通过pod 
#  pod 'flutter_lib', :path => '../flutter_lib'

end
